openapi: 3.0.0
info:
  title: OPA data API
  version: 0.0.0
servers:
  - url: http://localhost:8080
    description: Default endpoint
paths:
  /v1/data/{scope}:
    post:
      operationId: evaluateDocument
      summary: calls https://www.openpolicyagent.org/docs/latest/rest-api/#get-a-document-with-input internally
      description: |
        The given scope, request, client_id and verifier_id are used to create the input document for the OPA policy.
      tags:
        - opa
      parameters:
        - name: scope
          in: path
          required: true
          description: maps to the package of the OPA policy
          content:
            plain/text:
              schema:
                type: string
                example: test
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Input'
      responses:
        '200':
          description: Successful request. Returns the result of the OPA policy evaluation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Outcome'
components:
  schemas:
    Input:
      type: object
      required:
        - request
        - client_id
        - verifier_id
        - x_user_info
      properties:
        request:
          type: object
          description: The http request
        client_id:
          type: string
          description: client DID (for now)
          example: did:web:example.com:iam:client
        verifier_id:
          type: string
          description: verifier DID (for now)
          example: did:web:example.com:iam:verifier
        x_user_info:
          type: object
          description: Result from token introspection
    Outcome:
      type: object
      required:
        - allow
      properties:
        allow:
          type: boolean
          description: The result of the OPA policy evaluation
          example: true