openapi: 3.0.0
info:
  title: OPA data API
  version: 0.0.0
servers:
  - url: http://localhost:8080
    description: Default endpoint
paths:
  /v1/data:
    post:
      operationId: evaluateDocument
      summary: calls https://www.openpolicyagent.org/docs/latest/rest-api/#get-a-document-with-input internally
      description: |
        The given request and X-Userinfo headers are used to create the input document for the OPA policy.
      tags:
        - opa
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Input'
      responses:
        '200':
          description: Successful request. Returns the result of the OPA policy evaluation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Outcome'
  /v1/data/apisix:
    post:
      operationId: evaluateDocumentApisix
      summary: calls https://www.openpolicyagent.org/docs/latest/rest-api/#get-a-document-with-input internally
      description: |
        The given request and X-Userinfo headers are used to create the input document for the OPA policy.
      tags:
        - opa
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Input'
      responses:
        '200':
          description: Successful request. Returns the result of the OPA policy evaluation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Outcome'
components:
  schemas:
    Input:
      type: object
      required:
        - input
      properties:
        input:
          type: object
          description: Policy decision information. Must contain the fields in the example.
          example: |
            {
              "input": { 
                "request": {
                  "method": "GET", 
                  "path": "/resource", 
                  "headers": {
                    "X-Userinfo": "base64 encoded user info"
                  }
                }
              } 
            }
    Outcome:
      type: object
      required:
        - result
      properties:
        result:
          type: object
          description: The result of the OPA policy evaluation
          example: |
            {
              "result": {
                "allow": true
              }
            }