openapi: 3.0.0
info:
  title: PIP data API
  version: 0.0.0
servers:
  - url: http://localhost:8080
    description: Default endpoint
paths:
  /pip/{id}:
    parameters:
      - name: id
        in: path
        required: true
        description: An identifier for the data, used for deletion and updates
        content:
          plain/text:
            schema:
              type: string
              example: 1111-2222-3333-4444
    get:
      operationId: getData
      summary: Get pip data for given ide
      tags:
        - pip
      responses:
        '200':
          description: Data known for id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Data'
    post:
      operationId: createData
      summary: Add authorization data used for OPA evaluation
      description: |
        Add data to the PIP.
      tags:
        - pip
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Data'
      responses:
        '204':
          description: Successful request. No content.
    delete:
      operationId: deleteData
      summary: Delete data for given id
      tags:
        - pip
      responses:
        '204':
          description: Successful request. No content.
components:
  schemas:
    Data:
      type: object
      required:
        - scope
        - client_id
        - verifier_id
        - auth_input
      properties:
        scope:
          type: string
          description: The scope. Corresponds to the auth scopes
        client_id:
          type: string
          description: client DID (for now)
          example: did:web:example.com:iam:client
        verifier_id:
          type: string
          description: verifier DID (for now)
          example: did:web:example.com:iam:verifier
        auth_input:
          type: object
          description: Data used in OPA script